# Generated by Django 6.0.1 on 2026-05-02 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('SYNCED', 'Sincronizado')], default='DRAFT', max_length=20)),
                ('work_order', models.CharField(db_index=True, max_length=100, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('intervention_type', models.CharField(choices=[('INSTALLATION', 'Instalación'), ('MAINTENANCE', 'Mantenimiento'), ('REPAIR', 'Reparación'), ('INSPECTION', 'Inspección')], max_length=20)),
                ('location', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('materials_used', models.JSONField(default=list)),
                ('observations', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service report',
                'verbose_name_plural': 'service reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
