# Generated by Django 6.0.1 on 2026-05-02 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida'), ('ABORTED', 'Abortada')], default='ACTIVE', max_length=20)),
                ('model_used', models.CharField(default='claude-sonnet-4-6', max_length=100)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'agent session',
                'verbose_name_plural': 'agent sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('transcription', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conversation turn',
                'verbose_name_plural': 'conversation turns',
                'ordering': ['session', 'turn_index'],
            },
        ),
    ]
