# Generated by Django 6.0.1 on 2026-05-02 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agents.agentsession'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationturn',
            unique_together={('session', 'turn_index')},
        ),
    ]
